[0m14:47:00.556320 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F2AB220510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F2AB222910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F2AB222A90>]}


============================== 14:47:00.562286 | 895036e9-0316-425f-8d5d-2517e9d0a467 ==============================
[0m14:47:00.562286 [info ] [MainThread]: Running with dbt=1.10.9
[0m14:47:00.562286 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'use_colors': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'version_check': 'True', 'invocation_command': 'dbt ', 'log_format': 'default', 'warn_error': 'None', 'introspect': 'True', 'debug': 'False', 'printer_width': '80', 'fail_fast': 'False', 'no_print': 'None', 'use_experimental_parser': 'False', 'quiet': 'False', 'empty': 'None', 'log_cache_events': 'False', 'indirect_selection': 'eager', 'log_path': 'c:\\Users\\Eigenaar\\Documents\\Professional\\Data engineering\\1. Projects\\6. dbt and docker\\dbt-data-warehouse-project\\logs', 'write_json': 'True', 'static_parser': 'True', 'profiles_dir': 'c:\\Users\\Eigenaar\\Documents\\Professional\\Data engineering\\1. Projects\\6. dbt and docker\\dbt-data-warehouse-project'}
[0m14:47:00.738006 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '895036e9-0316-425f-8d5d-2517e9d0a467', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F2AB37E850>]}
[0m14:47:00.756663 [info ] [MainThread]: Warning: No packages were found in packages.yml
[0m14:47:00.762537 [info ] [MainThread]: Warning: No packages were found in packages.yml
[0m14:47:00.763595 [debug] [MainThread]: Command `cli deps` succeeded at 14:47:00.763595 after 0.33 seconds
[0m14:47:00.763595 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F2AB222190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F2AB351110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F2AA373250>]}
[0m14:47:00.763595 [debug] [MainThread]: Flushing usage events
[0m14:47:02.206833 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:50:56.149394 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D7B054C2D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D7AFC9EFD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D7B05A3D10>]}


============================== 14:50:56.157891 | ba7f8f4c-7cbb-4413-add9-cd7834b98d36 ==============================
[0m14:50:56.157891 [info ] [MainThread]: Running with dbt=1.10.9
[0m14:50:56.157891 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'write_json': 'True', 'send_anonymous_usage_stats': 'True', 'warn_error': 'None', 'cache_selected_only': 'False', 'target_path': 'None', 'use_colors': 'True', 'invocation_command': 'dbt ', 'log_format': 'default', 'version_check': 'True', 'introspect': 'True', 'debug': 'False', 'printer_width': '80', 'fail_fast': 'False', 'no_print': 'None', 'quiet': 'False', 'use_experimental_parser': 'False', 'log_cache_events': 'False', 'empty': 'None', 'log_path': 'c:\\Users\\Eigenaar\\Documents\\Professional\\Data engineering\\1. Projects\\6. dbt and docker\\dbt-data-warehouse-project\\logs', 'indirect_selection': 'eager', 'profiles_dir': 'c:\\Users\\Eigenaar\\Documents\\Professional\\Data engineering\\1. Projects\\6. dbt and docker\\dbt-data-warehouse-project', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])'}
[0m14:50:56.284441 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'ba7f8f4c-7cbb-4413-add9-cd7834b98d36', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D7B06F1D90>]}
[0m14:50:56.297479 [info ] [MainThread]: Warning: No packages were found in packages.yml
[0m14:50:56.297479 [info ] [MainThread]: Warning: No packages were found in packages.yml
[0m14:50:56.297479 [debug] [MainThread]: Command `cli deps` succeeded at 14:50:56.297479 after 0.25 seconds
[0m14:50:56.297479 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D7B05CFB90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D7B054E610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D7B054C510>]}
[0m14:50:56.297479 [debug] [MainThread]: Flushing usage events
[0m14:50:57.304062 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:52:03.790030 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BE776CCA50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BE7772BE50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BE7772BED0>]}


============================== 14:52:03.794040 | 26f7469c-ad74-46da-8dc0-be854f54a6b6 ==============================
[0m14:52:03.794040 [info ] [MainThread]: Running with dbt=1.10.9
[0m14:52:03.795042 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'use_colors': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'version_check': 'True', 'invocation_command': 'dbt parse', 'log_format': 'default', 'warn_error': 'None', 'introspect': 'True', 'debug': 'False', 'log_cache_events': 'False', 'fail_fast': 'False', 'no_print': 'None', 'empty': 'None', 'use_experimental_parser': 'False', 'quiet': 'False', 'printer_width': '80', 'log_path': 'C:\\Users\\Eigenaar\\Documents\\Professional\\Data engineering\\1. Projects\\6. dbt and docker\\dbt-data-warehouse-project\\logs', 'indirect_selection': 'eager', 'write_json': 'True', 'static_parser': 'True', 'profiles_dir': 'C:\\Users\\Eigenaar\\Documents\\Professional\\Data engineering\\1. Projects\\6. dbt and docker\\dbt-data-warehouse-project'}
[0m14:52:03.800961 [error] [MainThread]: Encountered an error:
Parsing Error
  Env var required but not provided: 'DBT_HOST'
[0m14:52:03.802374 [debug] [MainThread]: Command `dbt parse` failed at 14:52:03.802374 after 0.14 seconds
[0m14:52:03.802374 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BE7772F8D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BE776CC4D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BE70A3DFD0>]}
[0m14:52:03.803570 [debug] [MainThread]: Flushing usage events
[0m14:52:04.812858 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:52:21.649529 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F11B3DD6D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F11B3DDAD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F11B3DD2D0>]}


============================== 14:52:21.653529 | 17b6fde5-ef69-4287-abda-d2352b586d0d ==============================
[0m14:52:21.653529 [info ] [MainThread]: Running with dbt=1.10.9
[0m14:52:21.654530 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'write_json': 'True', 'send_anonymous_usage_stats': 'True', 'use_colors': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'warn_error': 'None', 'invocation_command': 'dbt parse', 'log_format': 'default', 'version_check': 'True', 'introspect': 'True', 'debug': 'False', 'printer_width': '80', 'fail_fast': 'False', 'no_print': 'None', 'use_experimental_parser': 'False', 'quiet': 'False', 'log_cache_events': 'False', 'empty': 'None', 'log_path': 'C:\\Users\\Eigenaar\\Documents\\Professional\\Data engineering\\1. Projects\\6. dbt and docker\\dbt-data-warehouse-project\\logs', 'indirect_selection': 'eager', 'profiles_dir': 'C:\\Users\\Eigenaar\\Documents\\Professional\\Data engineering\\1. Projects\\6. dbt and docker\\dbt-data-warehouse-project', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True'}
[0m14:52:22.031171 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '17b6fde5-ef69-4287-abda-d2352b586d0d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F11B3D72D0>]}
[0m14:52:22.092506 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '17b6fde5-ef69-4287-abda-d2352b586d0d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F117D99510>]}
[0m14:52:22.093512 [info ] [MainThread]: Registered adapter: sqlserver=1.9.0
[0m14:52:22.407724 [debug] [MainThread]: checksum: 6543b8b248ceda473ef0d611849d5d909085b6b714afa9b515e9635faea7af23, vars: {}, profile: , target: , version: 1.10.9
[0m14:52:22.407724 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m14:52:22.415799 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '17b6fde5-ef69-4287-abda-d2352b586d0d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F11CB33B90>]}
[0m14:52:24.076931 [warn ] [MainThread]: [[33mWARNING[0m]: 'crm_cust_info' is a seed node, but it is specified in the models section of
models\silver\schema.yml. To fix this error, place the `crm_cust_info`
specification under the seeds key instead.
[0m14:52:24.077897 [warn ] [MainThread]: [[33mWARNING[0m]: 'crm_prd_info' is a seed node, but it is specified in the models section of
models\silver\schema.yml. To fix this error, place the `crm_prd_info`
specification under the seeds key instead.
[0m14:52:24.077897 [warn ] [MainThread]: [[33mWARNING[0m]: 'crm_sales_details' is a seed node, but it is specified in the models section of
models\silver\schema.yml. To fix this error, place the `crm_sales_details`
specification under the seeds key instead.
[0m14:52:24.077897 [warn ] [MainThread]: [[33mWARNING[0m]: 'erp_cust_az12' is a seed node, but it is specified in the models section of
models\silver\schema.yml. To fix this error, place the `erp_cust_az12`
specification under the seeds key instead.
[0m14:52:24.084682 [warn ] [MainThread]: [[33mWARNING[0m]: 'erp_loc_a101' is a seed node, but it is specified in the models section of
models\silver\schema.yml. To fix this error, place the `erp_loc_a101`
specification under the seeds key instead.
[0m14:52:24.086651 [warn ] [MainThread]: [[33mWARNING[0m]: 'erp_px_cat_g1v2' is a seed node, but it is specified in the models section of
models\silver\schema.yml. To fix this error, place the `erp_px_cat_g1v2`
specification under the seeds key instead.
[0m14:52:24.090648 [warn ] [MainThread]: [[33mWARNING[0m][MissingArgumentsPropertyInGenericTestDeprecation]: Deprecated
functionality
Found top-level arguments to test `accepted_values`. Arguments to generic tests
should be nested under the `arguments` property.`
[0m14:52:24.091180 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'deprecation', 'label': '17b6fde5-ef69-4287-abda-d2352b586d0d', 'property_': 'warn', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F11D517D10>]}
[0m14:52:24.249279 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '17b6fde5-ef69-4287-abda-d2352b586d0d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F11CCA7910>]}
[0m14:52:24.253287 [info ] [MainThread]: Performance info: C:\Users\Eigenaar\Documents\Professional\Data engineering\1. Projects\6. dbt and docker\dbt-data-warehouse-project\target\perf_info.json
[0m14:52:24.400271 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\Eigenaar\Documents\Professional\Data engineering\1. Projects\6. dbt and docker\dbt-data-warehouse-project\target\manifest.json
[0m14:52:24.403276 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\Eigenaar\Documents\Professional\Data engineering\1. Projects\6. dbt and docker\dbt-data-warehouse-project\target\semantic_manifest.json
[0m14:52:24.404276 [warn ] [MainThread]: [[33mWARNING[0m][DeprecationsSummary]: Deprecated functionality
Summary of encountered deprecations:
- MissingArgumentsPropertyInGenericTestDeprecation: 4 occurrences
To see all deprecation instances instead of just the first occurrence of each,
run command again with the `--show-all-deprecations` flag. You may also need to
run with `--no-partial-parse` as some deprecations are only encountered during
parsing.
[0m14:52:24.405276 [debug] [MainThread]: Command `dbt parse` succeeded at 14:52:24.405276 after 2.85 seconds
[0m14:52:24.406276 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F11B4597D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F114AA93D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F11D5B3B50>]}
[0m14:52:24.406276 [debug] [MainThread]: Flushing usage events
[0m14:52:25.242962 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:56:21.461196 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000249BACFCC50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000249B9D2EA90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000249BAD37690>]}


============================== 14:56:21.466820 | 3d5b4bc0-f6a8-476d-9bb2-f53900e2f64a ==============================
[0m14:56:21.466820 [info ] [MainThread]: Running with dbt=1.10.9
[0m14:56:21.468097 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True', 'version_check': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'warn_error': 'None', 'invocation_command': 'dbt ', 'log_format': 'default', 'use_colors': 'True', 'introspect': 'True', 'debug': 'False', 'log_cache_events': 'False', 'fail_fast': 'False', 'no_print': 'None', 'quiet': 'False', 'use_experimental_parser': 'False', 'printer_width': '80', 'empty': 'None', 'log_path': 'c:\\Users\\Eigenaar\\Documents\\Professional\\Data engineering\\1. Projects\\6. dbt and docker\\dbt-data-warehouse-project\\logs', 'indirect_selection': 'eager', 'profiles_dir': 'c:\\Users\\Eigenaar\\Documents\\Professional\\Data engineering\\1. Projects\\6. dbt and docker\\dbt-data-warehouse-project', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'write_json': 'True'}
[0m14:56:21.613110 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '3d5b4bc0-f6a8-476d-9bb2-f53900e2f64a', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000249B76DADD0>]}
[0m14:56:21.625172 [info ] [MainThread]: Warning: No packages were found in packages.yml
[0m14:56:21.625172 [info ] [MainThread]: Warning: No packages were found in packages.yml
[0m14:56:21.625172 [debug] [MainThread]: Command `cli deps` succeeded at 14:56:21.625172 after 0.28 seconds
[0m14:56:21.625172 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000249BAD7BA50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000249BACFE990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000249BAD34510>]}
[0m14:56:21.625172 [debug] [MainThread]: Flushing usage events
[0m14:56:22.625608 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:57:50.233659 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F84517C990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F84419EB50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F845175CD0>]}


============================== 14:57:50.242226 | 78d21e1a-cb51-4ef8-8bdf-58c13a8f2b81 ==============================
[0m14:57:50.242226 [info ] [MainThread]: Running with dbt=1.10.9
[0m14:57:50.242226 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'profiles_dir': 'c:\\Users\\Eigenaar\\Documents\\Professional\\Data engineering\\1. Projects\\6. dbt and docker\\dbt-data-warehouse-project', 'send_anonymous_usage_stats': 'True', 'use_colors': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'warn_error': 'None', 'invocation_command': 'dbt ', 'log_format': 'default', 'version_check': 'True', 'introspect': 'True', 'debug': 'False', 'log_cache_events': 'False', 'fail_fast': 'False', 'no_print': 'None', 'use_experimental_parser': 'False', 'quiet': 'False', 'empty': 'None', 'printer_width': '80', 'indirect_selection': 'eager', 'log_path': 'c:\\Users\\Eigenaar\\Documents\\Professional\\Data engineering\\1. Projects\\6. dbt and docker\\dbt-data-warehouse-project\\logs', 'write_json': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])'}
[0m14:57:50.364559 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '78d21e1a-cb51-4ef8-8bdf-58c13a8f2b81', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8451FFD90>]}
[0m14:57:50.380129 [info ] [MainThread]: Warning: No packages were found in packages.yml
[0m14:57:50.396492 [info ] [MainThread]: Warning: No packages were found in packages.yml
[0m14:57:50.397500 [debug] [MainThread]: Command `cli deps` succeeded at 14:57:50.397500 after 0.26 seconds
[0m14:57:50.399044 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8451FFF50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F845261F50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F8462FBF10>]}
[0m14:57:50.399044 [debug] [MainThread]: Flushing usage events
[0m14:57:51.401652 [debug] [MainThread]: An error was encountered while trying to flush usage events
